[package]
name = "icn-network"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "src",
    "crates/core/icn-common",
    "crates/core/icn-crypto",
    "crates/core/icn-data-structures",
    "crates/core/icn-serialization",
    "crates/identity/icn-did",
    "crates/identity/icn-credentials",
    "crates/identity/icn-zkp",
    "crates/identity/icn-identity-system",
    "crates/governance/icn-governance-dsl",
    "crates/governance/icn-governance-vm",
    "crates/governance/icn-voting",
    "crates/governance/icn-governance-system",
    "crates/economic/icn-mutual-credit",
    "crates/economic/icn-transactions",
    "crates/economic/icn-confidential-tx",
    "crates/economic/icn-economic-system",
    "crates/node/icn-node-core",
    "crates/node/icn-node-cli",
    "crates/node/icn-node",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["ICN Developers <dev@icn.coop>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icn/intercooperative-network"

[workspace.dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

# Crypto
rand = "0.8"
sha2 = "0.10"
ed25519-dalek = "1.0"
k256 = "0.11"

# Data structures
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite"] }

# Testing
proptest = "1.0"
