[package]
name = "icn-networking"
version = "0.1.0"
edition = "2021"
description = "Networking layer for ICN with TLS 1.3 support"

[dependencies]
# Core dependencies
tokio = { version = "1.36", features = ["full"] }
tokio-rustls = "0.25"
rustls = { version = "0.22", features = ["tls12"] }
webpki-roots = "0.26"
futures = "0.3"
async-trait = "0.1"

# Error handling
thiserror = "1.0"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Logging
tracing = "0.1"

# ICN dependencies
icn-common = { path = "../../core/icn-common" }

[dev-dependencies]
tokio-test = "0.4"
