[package]
name = "icn-node"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Main node binary for ICN"

[dependencies]
# Internal dependencies
icn-common = { path = "../../core/icn-common" }
icn-node-core = { path = "../icn-node-core" }

# External dependencies
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
clap = { version = "4.0", features = ["derive"] }
serde.workspace = true
serde_json = "1.0"
toml = "0.7"

[features]
default = ["std", "mesh-network"]
std = []
mesh-network = []
hardware-acceleration = []
