[package]
name = "icn-cli"
version = "0.1.0"
edition = "2021"
description = "ICN Command Line Interface"
authors = ["ICN Developers"]
license = "MIT OR Apache-2.0"

[dependencies]
icn-core = { path = "../../crates/core" }
icn-identity = { path = "../../crates/identity" }
icn-ledger = { path = "../../crates/ledger" }
icn-governance = { path = "../../crates/governance" }
icn-network = { path = "../../crates/network" }
icn-apps = { path = "../../crates/apps" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.4", features = ["derive"] }

# TUI (Terminal User Interface)
ratatui = "0.22"
crossterm = "0.26"

[[bin]]
name = "icn-cli"
path = "src/main.rs"

[dev-dependencies]
tokio-test = "0.4" 