[package]
name = "icn-cli"
version = "0.1.0"
edition = "2021"
description = "ICN Command Line Interface"
authors = ["ICN Developers"]
license = "MIT OR Apache-2.0"

[dependencies]
icn-core = { path = "../../crates/core" }
icn-identity = { path = "../../crates/identity" }
icn-ledger = { path = "../../crates/ledger" }
icn-governance = { path = "../../crates/governance" }
icn-network = { path = "../../crates/network" }
icn-apps = { path = "../../crates/apps" }
icn-storage-system = { path = "../../crates/storage/icn-storage-system" }

tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.4", features = ["derive"] }
env_logger = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Time handling
chrono = "0.4"

# UUID generation
uuid = { version = "1.4", features = ["v4"] }

# Encryption
chacha20poly1305 = { workspace = true }
aes-gcm = { workspace = true }
rand_core = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }

# Key derivation and encoding
base64 = "0.21"
hkdf = "0.12"
x25519-dalek = "2.0.0"
argon2 = "0.5"

# Password hashing
pbkdf2 = "0.12"

# TUI (Terminal User Interface)
ratatui = "0.22"
crossterm = "0.26"

# Network-specific dependencies
libp2p = { version = "0.55", features = ["tcp", "dns", "websocket", "noise", "yamux", "ping", "identify", "kad", "gossipsub", "mdns", "tokio"] }
wireguard-control = "1.5.0"
async-trait = "0.1.73"
multiaddr = "0.17.1"
futures = "0.3.28"
hex = "0.4.3"
ipnetwork = "0.20.0"

[[bin]]
name = "icn-cli"
path = "src/main.rs"

[dev-dependencies]
tokio-test = "0.4" 