apiVersion: v1
kind: ConfigMap
metadata:
  name: icn-config
  namespace: icn-system
data:
  node.yaml.template: |
    node_id: ${ICN_NODE_ID}
    coop_id: ${ICN_COOP_ID}
    node_type: ${ICN_NODE_TYPE}
    listen_addr: ${ICN_LISTEN_ADDR}
    log_level: ${ICN_LOG_LEVEL}
    data_dir: /var/lib/icn
    tls:
      enabled: true
      cert_file: /etc/icn/certs/node.crt
      key_file: /etc/icn/certs/node.key
      ca_file: /etc/icn/certs/ca.crt 