[package]
name = "icn-storage-system"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Storage system for ICN"

[dependencies]
# Internal dependencies
icn-common = { path = "../../core/icn-common" }

# External dependencies
async-trait = "0.1"
tokio = { version = "1.0", features = ["fs", "sync", "io-util"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.8"
tokio = { version = "1.0", features = ["full", "test-util"] }