apiVersion: v1
kind: ConfigMap
metadata:
  name: icn-config
  namespace: icn-system
data:
  node.yaml.template: |
    # Node Identity Configuration
    node_id: "${ICN_NODE_ID:-node-0}"
    coop_id: "${ICN_COOP_ID:-coop-0}"
    node_type: "${ICN_NODE_TYPE:-primary}"

    # Network Configuration
    listen_addr: "${ICN_LISTEN_ADDR:-0.0.0.0:9000}"
    peers: ${ICN_PEERS:-[]}
    discovery_interval: ${ICN_DISCOVERY_INTERVAL:-30}  # seconds
    health_check_interval: ${ICN_HEALTH_CHECK_INTERVAL:-10}  # seconds

    # Storage Configuration
    data_dir: "${ICN_DATA_DIR:-/var/lib/icn}"
    cert_dir: "${ICN_CERT_DIR:-/etc/icn/certs}"

    # Logging Configuration
    log_dir: "${ICN_LOG_DIR:-/var/log/icn}"
    log_level: "${ICN_LOG_LEVEL:-info}"

    # TLS Configuration
    tls:
      cert_file: "/etc/icn/certs/node.crt"
      key_file: "/etc/icn/certs/node.key"
      ca_file: "/etc/icn/certs/ca.crt"
      verify_client: ${ICN_VERIFY_CLIENT:-true}
      verify_hostname: ${ICN_VERIFY_HOSTNAME:-true}

    # Resource Limits
    limits:
      max_connections: ${ICN_MAX_CONNECTIONS:-1000}
      max_message_size: ${ICN_MAX_MESSAGE_SIZE:-1048576}  # 1MB
      max_peers: ${ICN_MAX_PEERS:-100} 