apiVersion: v1
kind: Service
metadata:
  name: coop2-secondary
  namespace: icn-network-20250313014229
  labels:
    app: icn
    component: node
    coop: coop-2
    role: secondary
spec:
  selector:
    app: icn
    component: node
    coop: coop-2
    role: secondary
  ports:
  - port: 9003
    targetPort: 9003
    name: p2p
  type: ClusterIP 