apiVersion: v1
kind: Service
metadata:
  name: coop1-primary
  namespace: icn-network-20250313014229
  labels:
    app: icn
    component: node
    coop: coop-1
    role: primary
spec:
  selector:
    app: icn
    component: node
    coop: coop-1
    role: primary
  ports:
  - port: 9000
    targetPort: 9000
    name: p2p
  type: ClusterIP 