apiVersion: v1
kind: Service
metadata:
  name: coop2-primary
  namespace: icn-network-20250313014229
  labels:
    app: icn
    component: node
    coop: coop-2
    role: primary
spec:
  selector:
    app: icn
    component: node
    coop: coop-2
    role: primary
  ports:
  - port: 9002
    targetPort: 9002
    name: p2p
  type: ClusterIP 