# Node Configuration for node-003
node_id: "node-003"
node_type: "full"
listen_addr: "/ip6/::1/tcp/9003"
peer_id: "d6f8406df69dc77d91071bc015d901a3"
data_dir: "./data/icn/node-003"
log_dir: "./data/log/icn"
network_config_path: "./config/icn-testnet-ipv6.yaml"
